tokenizer:
  source: ./models/mllama_t
  pad_to_multiple_of: 8
models:
  - model: ./models/mllama_t
    parameters:
      weight: 1.0
      density: 0.8
  - model: ./models/tulu_t
    parameters:
      density: 0.8
      weight:
        - filter: lm_head
          value: 0
        - value: 1.0
merge_method: dare_linear
parameters:
  normalize: false
base_model: meta-llama/Llama-3.1-8B
dtype: float32
