tokenizer:
  source: ./models/mllama_t
  pad_to_multiple_of: 8
models:
  - model: ./models/mllama_t
    parameters:
      weight: 0.5
  - model: ./models/tulu_t
    parameters:
      weight:
        - filter: lm_head
          value: 0
        - value: 0.5
merge_method: task_arithmetic
parameters:
  normalize: false
base_model: meta-llama/Llama-3.1-8B
dtype: float32
